- hosts: automatiza-projeto
  tasks:
  - name: Instalando o pyhton3, virtualenv
    apt:
      pkg:
      - python3
      - virtualenv
      update_cache: yes
    become: true

  - name: Git Clone
    ansible.builtin.git:
      repo: https://github.com/ssdvd/app-cadastro-django.git
      dest: /home/ubuntu/djangoapp
      version: main
      force: yes

  - name: Instalando dependencias com pip
    pip:
      virtualenv: /home/ubuntu/djangoapp/app-cadastro-django/venv
      requirements: /home/ubuntu/djangoapp/app-cadastro-django/requirements.txt

  - name: iniciando o servidor
    shell: '. /home/ubuntu/djangoapp/app-cadastro-django/venv/bin/activate; nohup python3 /home/ubuntu/djangoapp/app-cadastro-django/manage.py runserver 0.0.0.0/8000 &' 