name: djangoapp

# Define os eventos que acionarão o fluxo
on:
  push:
    branches: [ "actions-ecs" ]  # Aciona o fluxo quando houver push na branch 'actions-ecs'
  pull_request:
    branches: [ "actions-ecs" ]  # Aciona o fluxo quando houver pull request na branch 'actions-ecs'

# Define os jobs que serão executados
jobs:
  testes:  # Job para executar os testes

    runs-on: ubuntu-latest  # Usa a última versão do Ubuntu para rodar este job
    steps:
    - uses: actions/checkout@v4  # Passo para realizar checkout do repositório

    - name: Setando Python  # Configuração do ambiente Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.12  # Utiliza a versão 3.10.12 do Python

    - name: Instalando Dependencias  # Instalação das dependências do projeto
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Rodando Testes  # Execução dos testes #python manage.py test
      run: |
        nohup python manage.py runserver 0.0.0.0:8000 & 

  server:  # Job para rodar o servidor

    needs: testes  # Dependência do job 'testes', ou seja, este job só é executado se 'testes' for bem-sucedido
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setando Python 
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.12

    - name: Instalando Dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Rodando Server  # Inicia o servidor Django
      run: |
        nohup python manage.py runserver 0.0.0.0:8000 &

  docker:  # Job para construir e enviar a imagem Docker

    needs: server  # Dependência do job 'server', só é executado se 'server' for bem-sucedido
    uses: ./.github/workflows/docker.yml  # Utiliza o arquivo docker.yml local para as instruções
    secrets: inherit  # Herda os segredos do job anterior (server)

  ecs:  # Job para implantar no Amazon ECS

    needs: docker  # Dependência do job 'docker', só é executado se 'docker' for bem-sucedido
    uses: ./.github/workflows/ecs.yml  # Utiliza o arquivo ecs.yml local para as instruções
    secrets: inherit  # Herda os segredos do job anterior (docker)
